/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum9;

/**
 *
 * @author Andika Bayu S
 */
public class Kalkulator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kalkulator.class.getName());

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
        txhasil.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNilai1 = new javax.swing.JLabel();
        lbNilai2 = new javax.swing.JLabel();
        lbHasil = new javax.swing.JLabel();
        txnilai2 = new javax.swing.JTextField();
        txhasil = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnPangkat = new javax.swing.JButton();
        btnAkar = new javax.swing.JButton();
        txnilai1 = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kallkulator Mini");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNilai1.setText("Nilai Pertama");
        getContentPane().add(lbNilai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 38, -1, -1));

        lbNilai2.setText("Nilai Kedua");
        getContentPane().add(lbNilai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 73, -1, -1));

        lbHasil.setText("Hasil");
        getContentPane().add(lbHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 113, -1, -1));

        txnilai2.setColumns(3);
        txnilai2.addActionListener(this::txnilai2ActionPerformed);
        getContentPane().add(txnilai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 70, 110, -1));

        txhasil.setColumns(3);
        txhasil.addActionListener(this::txhasilActionPerformed);
        getContentPane().add(txhasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 110, 110, -1));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        btnKali.setText("Kali");
        btnKali.addActionListener(this::btnKaliActionPerformed);
        getContentPane().add(btnKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 74, -1));

        btnBagi.setText("Bagi");
        btnBagi.addActionListener(this::btnBagiActionPerformed);
        getContentPane().add(btnBagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 74, -1));

        btnKurang.setText("Kurang");
        btnKurang.addActionListener(this::btnKurangActionPerformed);
        getContentPane().add(btnKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 74, -1));

        btnPangkat.setText("Pangkat");
        btnPangkat.addActionListener(this::btnPangkatActionPerformed);
        getContentPane().add(btnPangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        btnAkar.setText("Akar");
        btnAkar.addActionListener(this::btnAkarActionPerformed);
        getContentPane().add(btnAkar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 73, -1));

        txnilai1.setColumns(3);
        txnilai1.addActionListener(this::txnilai1ActionPerformed);
        getContentPane().add(txnilai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 35, 110, -1));

        btnhapus.setText("Kosong");
        btnhapus.addActionListener(this::btnhapusActionPerformed);
        getContentPane().add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 165, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txhasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txhasilActionPerformed

    private void txnilai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnilai2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnilai2ActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        double[] input = validasiDanAmbilInput(true);
        if (input != null) {
            double hasil = input[0] + input[1];
            txhasil.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        // TODO add your handling code here:
        double[] input = validasiDanAmbilInput(true);
        if (input != null) {
        // Validasi pembagian dengan nol
        if (input[1] == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Tidak dapat membagi dengan angka nol!", "Error Arithmetic", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        double hasil = input[0] / input[1];
        txhasil.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_btnBagiActionPerformed

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        // TODO add your handling code here:
        double[] input = validasiDanAmbilInput(true);
        if (input != null) {
            double hasil = input[0] - input[1];
            txhasil.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
        // TODO add your handling code here:
        double[] input = validasiDanAmbilInput(true);
        if (input != null) {
            double hasil = input[0] * input[1];
            txhasil.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_btnKaliActionPerformed

    private void btnPangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPangkatActionPerformed
        // TODO add your handling code here:
        double[] input = validasiDanAmbilInput(true);
        if (input != null) {
            double hasil = Math.pow(input[0], input[1]);
            txhasil.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_btnPangkatActionPerformed

    private void btnAkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkarActionPerformed
        // TODO add your handling code here:
        // Masukkan 'false' karena operasi akar kuadrat hanya membutuhkan Nilai Pertama
        double[] input = validasiDanAmbilInput(false); 
        if (input != null) {
        // Validasi angka negatif di dalam akar kuadrat riil
        if (input[0] < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nilai pertama tidak boleh negatif untuk operasi akar!", "Error Math", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        double hasil = Math.sqrt(input[0]);
        txhasil.setText(String.valueOf(hasil));
        }
    }//GEN-LAST:event_btnAkarActionPerformed

    private void txnilai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnilai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnilai1ActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        // Mengosongkan text field Nilai Pertama, Nilai Kedua, dan Hasil
    txnilai1.setText("");
    txnilai2.setText("");
    txhasil.setText("");
    
    // Opsional: Mengembalikan kursor fokus ke inputan pertama agar user bisa langsung mengetik lagi
    txnilai1.requestFocus();
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kalkulator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAkar;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnPangkat;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnhapus;
    private javax.swing.JLabel lbHasil;
    private javax.swing.JLabel lbNilai1;
    private javax.swing.JLabel lbNilai2;
    private javax.swing.JTextField txhasil;
    private javax.swing.JTextField txnilai1;
    private javax.swing.JTextField txnilai2;
    // End of variables declaration//GEN-END:variables

// Method pembantu untuk mengecek input kosong dan format angka
private double[] validasiDanAmbilInput(boolean butuhInput2) {
    String str1 = txnilai1.getText().trim();
    String str2 = txnilai2.getText().trim();

    // 1. Cek Apakah Input Kosong
    if (str1.isEmpty() || (butuhInput2 && str2.isEmpty())) {
        javax.swing.JOptionPane.showMessageDialog(this, "Inputan msh kosong", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return null; // Mengembalikan null sebagai tanda validasi gagal
    }

    try {
        // 2. Cek Apakah Format Angka Valid (Mencegah Error Huruf)
        double n1 = Double.parseDouble(str1);
        double n2 = butuhInput2 ? Double.parseDouble(str2) : 0;
        return new double[]{n1, n2};
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Masukkan format angka yang valid!", "Error Input", javax.swing.JOptionPane.ERROR_MESSAGE);
        return null;
    }
}
}