/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum9;

/**
 *
 * @author Andika Bayu S
 */
public class Mahasiswa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Mahasiswa.class.getName());

    /**
     * Creates new form Mahasiswa
     */
    public Mahasiswa() {
        initComponents();
        txhitungtugas.setEditable(false);
        txhitunguts.setEditable(false);
        txhitunguas.setEditable(false);
        txnilaiakhir.setEditable(false);
        txnilaihuruf.setEditable(false);
        txpredikat.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbnama = new javax.swing.JLabel();
        lbnim = new javax.swing.JLabel();
        lbnilaitugas = new javax.swing.JLabel();
        lbnilaiuts = new javax.swing.JLabel();
        lbnilaiuas = new javax.swing.JLabel();
        lbnilaiakhir = new javax.swing.JLabel();
        lbnilaihuruf = new javax.swing.JLabel();
        lbpredikat = new javax.swing.JLabel();
        txnim = new javax.swing.JTextField();
        txnama = new javax.swing.JTextField();
        txnilaitugas = new javax.swing.JTextField();
        txnilaiuts = new javax.swing.JTextField();
        txnilaiuas = new javax.swing.JTextField();
        txnilaiakhir = new javax.swing.JTextField();
        txnilaihuruf = new javax.swing.JTextField();
        txpredikat = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txhitungtugas = new javax.swing.JTextField();
        txhitunguts = new javax.swing.JTextField();
        txhitunguas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Nilai");

        lbnama.setText("Nama");

        lbnim.setText("Nim");

        lbnilaitugas.setText("Nilai Tugas");

        lbnilaiuts.setText("Nilai UTS");

        lbnilaiuas.setText("Nilai UAS");

        lbnilaiakhir.setText("Nilai Akhir");

        lbnilaihuruf.setText("Nilai Huruf");

        lbpredikat.setText("Predikat");

        txnim.addActionListener(this::txnimActionPerformed);

        txnama.addActionListener(this::txnamaActionPerformed);

        txnilaitugas.setColumns(3);
        txnilaitugas.addActionListener(this::txnilaitugasActionPerformed);

        txnilaiuts.setColumns(3);
        txnilaiuts.addActionListener(this::txnilaiutsActionPerformed);

        txnilaiuas.setColumns(3);
        txnilaiuas.addActionListener(this::txnilaiuasActionPerformed);

        txnilaiakhir.setColumns(3);
        txnilaiakhir.addActionListener(this::txnilaiakhirActionPerformed);

        txnilaihuruf.setColumns(3);
        txnilaihuruf.addActionListener(this::txnilaihurufActionPerformed);

        txpredikat.setColumns(5);
        txpredikat.addActionListener(this::txpredikatActionPerformed);

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(this::btnhitungActionPerformed);

        jLabel1.setText("30%");

        jLabel2.setText("35%");

        jLabel3.setText("35%");

        txhitungtugas.setColumns(4);
        txhitungtugas.addActionListener(this::txhitungtugasActionPerformed);

        txhitunguts.setColumns(4);
        txhitunguts.addActionListener(this::txhitungutsActionPerformed);

        txhitunguas.setColumns(4);
        txhitunguas.addActionListener(this::txhitunguasActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbnim, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txnim, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbnama, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(btnhitung))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbnilaitugas)
                .addGap(22, 22, 22)
                .addComponent(txnilaitugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txhitungtugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbnilaiuts)
                .addGap(33, 33, 33)
                .addComponent(txnilaiuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txhitunguts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbnilaiuas)
                .addGap(32, 32, 32)
                .addComponent(txnilaiuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txhitunguas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbnilaiakhir)
                .addGap(26, 26, 26)
                .addComponent(txnilaiakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbnilaihuruf)
                .addGap(23, 23, 23)
                .addComponent(txnilaihuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbpredikat)
                .addGap(38, 38, 38)
                .addComponent(txpredikat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbnim)
                    .addComponent(txnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbnama))
                    .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnhitung)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txnilaitugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txhitungtugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbnilaitugas)
                            .addComponent(jLabel1))))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbnilaiuts))
                    .addComponent(txnilaiuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txhitunguts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txnilaiuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txhitunguas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbnilaiuas)
                            .addComponent(jLabel3))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbnilaiakhir))
                    .addComponent(txnilaiakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbnilaihuruf))
                    .addComponent(txnilaihuruf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbpredikat))
                    .addComponent(txpredikat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnimActionPerformed

    private void txnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnamaActionPerformed

    private void txnilaitugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnilaitugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnilaitugasActionPerformed

    private void txnilaiutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnilaiutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnilaiutsActionPerformed

    private void txnilaiuasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnilaiuasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnilaiuasActionPerformed

    private void txnilaiakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnilaiakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnilaiakhirActionPerformed

    private void txnilaihurufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnilaihurufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnilaihurufActionPerformed

    private void txpredikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpredikatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpredikatActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        if (txnim.getText().trim().isEmpty() || 
            txnama.getText().trim().isEmpty() || 
            txnilaitugas.getText().trim().isEmpty() || 
            txnilaiuts.getText().trim().isEmpty() || 
            txnilaiuas.getText().trim().isEmpty()) {
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Semua data inputan (NIM, Nama, Tugas, UTS, UAS) wajib diisi!", 
                "Inputan msh kosong", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            // 2. Parsing nilai dari text field desain kamu
            float nilaiTugas = Float.parseFloat(txnilaitugas.getText());
            float nilaiUts = Float.parseFloat(txnilaiuts.getText());
            float nilaiUas = Float.parseFloat(txnilaiuas.getText());

            // Validasi batasan nilai antara 0 - 100 
            if (nilaiTugas < 0 || nilaiTugas > 100 || 
                nilaiUts < 0 || nilaiUts > 100 || 
                nilaiUas < 0 || nilaiUas > 100) {
                throw new IllegalArgumentException("Nilai harus berada dalam rentang 0 sampai 100!");
            }

            // 3. Logika perhitungan persentase bobot nilai temanmu
            float pNilaiTugas = 0.3f * nilaiTugas;
            float pNilaiUts = 0.35f * nilaiUts;
            float pNilaiUas = 0.35f * nilaiUas;

            // 4. Set hasil ke komponen text field hitung (sebelah kanan)
            txhitungtugas.setText(Float.toString(pNilaiTugas));
            txhitunguts.setText(Float.toString(pNilaiUts));
            txhitunguas.setText(Float.toString(pNilaiUas));

            // 5. Hitung nilai akhir kumulatif
            float nilaiAkhir = pNilaiTugas + pNilaiUts + pNilaiUas;
            txnilaiakhir.setText(Float.toString(nilaiAkhir));

            
            DataMahasiswa m = new DataMahasiswa();
            String nilaiHuruf = m.getNilHuruf(nilaiAkhir);
            
            txnilaihuruf.setText(nilaiHuruf);
            txpredikat.setText(m.getPredikat(nilaiHuruf));

        } catch (NumberFormatException e) {
            // Menangkap error jika user menginput huruf/karakter aneh pada kolom nilai 
            javax.swing.JOptionPane.showMessageDialog(this,
                "Input nilai tugas, UTS, dan UAS harus berupa angka!",
                "Kesalahan Format Input",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            // Menangkap error batasan rentang angka nilai 
            javax.swing.JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Kesalahan Range Nilai",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Menangkap error tidak terduga lainnya
            javax.swing.JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Kesalahan",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnhitungActionPerformed

    private void txhitungtugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txhitungtugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txhitungtugasActionPerformed

    private void txhitungutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txhitungutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txhitungutsActionPerformed

    private void txhitunguasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txhitunguasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txhitunguasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Mahasiswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbnama;
    private javax.swing.JLabel lbnilaiakhir;
    private javax.swing.JLabel lbnilaihuruf;
    private javax.swing.JLabel lbnilaitugas;
    private javax.swing.JLabel lbnilaiuas;
    private javax.swing.JLabel lbnilaiuts;
    private javax.swing.JLabel lbnim;
    private javax.swing.JLabel lbpredikat;
    private javax.swing.JTextField txhitungtugas;
    private javax.swing.JTextField txhitunguas;
    private javax.swing.JTextField txhitunguts;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txnilaiakhir;
    private javax.swing.JTextField txnilaihuruf;
    private javax.swing.JTextField txnilaitugas;
    private javax.swing.JTextField txnilaiuas;
    private javax.swing.JTextField txnilaiuts;
    private javax.swing.JTextField txnim;
    private javax.swing.JTextField txpredikat;
    // End of variables declaration//GEN-END:variables
}
