/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum11;

/**
 *
 * @author Andika Bayu S
 */
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel; 
import javax.swing.JOptionPane;

public class frmBarang extends javax.swing.JFrame {
Connection Con;
    ResultSet RsBrg;
    Statement stm;
    Boolean ada = false;
    String sSatuan;
    Boolean edit = false;
    private Object[][] dataTable = null;
    private String[] header = {"Kode", "Nama Barang", "Satuan", "Harga Beli", "Harga Jual", "Stok", "Stok Min"};
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmBarang.class.getName());
    /**
     * Creates new form frmBarang
     */
    public frmBarang() {
        initComponents();
        open_db();
        baca_data();
        aktif(false);
        setTombol(true);    
    }
    
    // PERBAIKAN: Nama komponen disesuaikan dengan deklarasi NetBeans (contoh: tblBrg -> jTable1)
    private void setField() {
    try {
        int row = tbl_barang.getSelectedRow();
        
        txt_kodebarang.setText(String.valueOf(tbl_barang.getValueAt(row, 0)));
        txt_namabarang.setText(String.valueOf(tbl_barang.getValueAt(row, 1)));
        cb_satuan.setSelectedItem(String.valueOf(tbl_barang.getValueAt(row, 2)));
        
        // Mengambil Harga Beli (Indeks 3)
        Object hrgBeliObj = tbl_barang.getValueAt(row, 3);
        txt_hargabeli.setText(hrgBeliObj != null ? String.valueOf(hrgBeliObj) : "");
        
        // Mengambil Harga Jual (Indeks 4)
        Object hrgJualObj = tbl_barang.getValueAt(row, 4);
        txt_hargajual.setText(hrgJualObj != null ? String.valueOf(hrgJualObj) : "");
        
        // Mengambil Stok dan Stok Minimal
        Object stokObj = tbl_barang.getValueAt(row, 5);
        txt_stok.setText(stokObj != null ? String.valueOf(stokObj) : "");
        
        Object stokMinObj = tbl_barang.getValueAt(row, 6);
        txt_stokminimal.setText(stokMinObj != null ? String.valueOf(stokMinObj) : "");
        
    } catch (Exception e) {
        System.out.println("Error pada setField: " + e.getMessage());
    }
    }

    // Method baca data dari Mysql dimasukkan ke jTable1
    private void baca_data() {
    try {
        stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        RsBrg = stm.executeQuery("select * from barang");
        ResultSetMetaData meta = RsBrg.getMetaData();
        int col = meta.getColumnCount();
        int baris = 0;
        while (RsBrg.next()) {
            baris = RsBrg.getRow();
        }
        dataTable = new Object[baris][col];
        int x = 0;
        RsBrg.beforeFirst();
        while (RsBrg.next()) {
            dataTable[x][0] = RsBrg.getString("kd_brg");
            dataTable[x][1] = RsBrg.getString("nm_brg");
            dataTable[x][2] = RsBrg.getString("satuan");
            dataTable[x][3] = RsBrg.getDouble("harga_beli"); // Kolom baru (indeks 3)
            dataTable[x][4] = RsBrg.getDouble("harga_jual"); // Bergeser ke indeks 4
            dataTable[x][5] = RsBrg.getInt("stok");          // Bergeser ke indeks 5
            dataTable[x][6] = RsBrg.getInt("stok_min");      // Bergeser ke indeks 6
            x++;
        }
        tbl_barang.setModel(new DefaultTableModel(dataTable, header));
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }

    // Untuk mengosongkan isian data
    private void kosong() {
        txt_kodebarang.setText("");
        txt_namabarang.setText("");
        txt_hargabeli.setText(""); // Tambahan
        txt_hargajual.setText("");
        txt_stok.setText("");
        txt_stokminimal.setText("");
    }

    // Mengatur aktif tidaknya isian data
    private void aktif(boolean x) {
        txt_kodebarang.setEditable(x);
        txt_namabarang.setEditable(x);
        cb_satuan.setEnabled(x);
        txt_hargabeli.setEditable(x); // Tambahan
        txt_hargajual.setEditable(x);
        txt_stok.setEditable(x);
        txt_stokminimal.setEditable(x);
    }

    // Mengatur tombol on/off
    private void setTombol(boolean t) {
        btn_tambah.setEnabled(t);
        btn_koreksi.setEnabled(t);
        btn_hapus.setEnabled(t);
        btn_simpan.setEnabled(!t);
        btn_batal.setEnabled(!t);
        btn_keluar.setEnabled(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_kodebarang = new javax.swing.JLabel();
        lb_namabarang = new javax.swing.JLabel();
        lb_satuan = new javax.swing.JLabel();
        lb_hargajual = new javax.swing.JLabel();
        lb_stok = new javax.swing.JLabel();
        lb_stokminimal = new javax.swing.JLabel();
        txt_kodebarang = new javax.swing.JTextField();
        txt_namabarang = new javax.swing.JTextField();
        cb_satuan = new javax.swing.JComboBox<>();
        txt_hargajual = new javax.swing.JTextField();
        txt_stok = new javax.swing.JTextField();
        txt_stokminimal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_barang = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_koreksi = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        txt_hargabeli = new javax.swing.JTextField();
        lb_satuan1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Data Barang");
        setName("R"); // NOI18N

        lb_kodebarang.setText("Kode Barang");

        lb_namabarang.setText("Nama Barang");

        lb_satuan.setText("Satuan");

        lb_hargajual.setText("Harga Jual");

        lb_stok.setText("Stok");

        lb_stokminimal.setText("Stok Minimal");

        txt_kodebarang.addActionListener(this::txt_kodebarangActionPerformed);

        cb_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monitor", "Laptop", "Keybord", "Mouse" }));
        cb_satuan.addActionListener(this::cb_satuanActionPerformed);

        tbl_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Barang", "Satuan", "Harga Beli", "Harga jual", "Stok", "StokMin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_barang.setName("tblBarang"); // NOI18N
        tbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_barang);

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(this::btn_tambahActionPerformed);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_koreksi.setText("Koreksi");
        btn_koreksi.addActionListener(this::btn_koreksiActionPerformed);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        btn_batal.setText("Batal");
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(this::btn_keluarActionPerformed);

        txt_hargabeli.addActionListener(this::txt_hargabeliActionPerformed);

        lb_satuan1.setText("Harga Beli");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_koreksi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_keluar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_kodebarang)
                        .addGap(57, 57, 57)
                        .addComponent(txt_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_satuan)
                            .addComponent(lb_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_stokminimal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_namabarang)
                            .addComponent(lb_hargajual)
                            .addComponent(lb_satuan1))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_stokminimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_kodebarang)
                    .addComponent(txt_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_namabarang)
                    .addComponent(txt_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_satuan)
                    .addComponent(cb_satuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_satuan1)
                    .addComponent(txt_hargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_hargajual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hargajual))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_stok)
                    .addComponent(txt_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_stokminimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_stokminimal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_simpan)
                    .addComponent(btn_koreksi)
                    .addComponent(btn_hapus)
                    .addComponent(btn_batal)
                    .addComponent(btn_keluar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_satuanActionPerformed
        // TODO add your handling code here:
        JComboBox cSatuan = (javax.swing.JComboBox)evt.getSource();
        sSatuan = (String)cSatuan.getSelectedItem();
    }//GEN-LAST:event_cb_satuanActionPerformed

    private void txt_kodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodebarangActionPerformed

    private void btn_koreksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_koreksiActionPerformed
        // TODO add your handling code here:
        edit=true;
        aktif(true);
        setTombol(false);
        txt_kodebarang.setEditable(false);
    }//GEN-LAST:event_btn_koreksiActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String tKode = txt_kodebarang.getText();
        String tNama = txt_namabarang.getText();
        String tSatuan = (String) cb_satuan.getSelectedItem();
    
        // Membaca input harga beli baru
        double hrgBeli = Double.parseDouble(txt_hargabeli.getText()); 
        double hrgJual = Double.parseDouble(txt_hargajual.getText());
        int stk = Integer.parseInt(txt_stok.getText());
        int stkMin = Integer.parseInt(txt_stokminimal.getText());
        
        try {
            if (edit == true) {
            // Query UPDATE disesuaikan dengan field harga_beli dan harga_jual
            stm.executeUpdate("UPDATE barang SET nm_brg='" + tNama + "', satuan='" + tSatuan + 
                              "', harga_beli=" + hrgBeli + ", harga_jual=" + hrgJual + 
                              ", stok=" + stk + ", stok_min=" + stkMin + 
                              " WHERE kd_brg='" + tKode + "'");
            } else {
            // Query INSERT disesuaikan dengan field harga_beli dan harga_jual
            stm.executeUpdate("INSERT INTO barang (kd_brg, nm_brg, satuan, harga_beli, harga_jual, stok, stok_min) VALUES('" 
                              + tKode + "', '" + tNama + "', '" + tSatuan + "', " + hrgBeli + ", " + hrgJual + ", " + stk + ", " + stkMin + ")");
            }
            
            baca_data();
            aktif(false);
            setTombol(true);
            edit = false;
            JOptionPane.showMessageDialog(null, "Data barang berhasil disimpan!");
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        aktif(true);
        setTombol(false);
        kosong();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        aktif(false);
        setTombol(true);
        edit = false;
    }//GEN-LAST:event_btn_batalActionPerformed

    private void tbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_barangMouseClicked
        // TODO add your handling code here:
        setField();
    }//GEN-LAST:event_tbl_barangMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql="delete from barang where kd_brg='" + txt_kodebarang.getText()+ "'";
            stm.executeUpdate(sql);
            baca_data();
            kosong(); // Tambahan opsional: mengosongkan form setelah dihapus
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void txt_hargabeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargabeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargabeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new frmBarang().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_koreksi;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cb_satuan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_hargajual;
    private javax.swing.JLabel lb_kodebarang;
    private javax.swing.JLabel lb_namabarang;
    private javax.swing.JLabel lb_satuan;
    private javax.swing.JLabel lb_satuan1;
    private javax.swing.JLabel lb_stok;
    private javax.swing.JLabel lb_stokminimal;
    private javax.swing.JTable tbl_barang;
    private javax.swing.JTextField txt_hargabeli;
    private javax.swing.JTextField txt_hargajual;
    private javax.swing.JTextField txt_kodebarang;
    private javax.swing.JTextField txt_namabarang;
    private javax.swing.JTextField txt_stok;
    private javax.swing.JTextField txt_stokminimal;
    // End of variables declaration//GEN-END:variables

    private void open_db() { 
    try {
        // Menggunakan kelas koneksi penjualan Anda
        KoneksiMysql kon = new KoneksiMysql("localhost", "root", "", "penjualan");
        Con = kon.getConnection();
    } catch (Exception e) {
        System.out.println("Error Koneksi: " + e.getMessage());
    }
    }
}
