/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum11;

import java.io.IOException;
import java.util.logging.*;
import javax.swing.*;

/**
 *
 * @author Andika Bayu S
 */
public class frmBackupDatabase extends javax.swing.JFrame {

    /**
     * Creates new form frmBackupDatabase
     */
    public frmBackupDatabase() {
        initComponents();
    }

    /**
     * Method untuk mencari path executable mysqldump secara otomatis di komputer.
     * Ini memastikan program berjalan baik di XAMPP, Laragon, maupun instalasi MySQL standar.
     */
    private String getMysqldumpPath() {
        String[] paths = {
            "D:/laragon/bin/mysql/mysql-8.0.30-winx64/bin/mysqldump.exe",
            "C:/xampp/mysql/bin/mysqldump.exe",
            "C:/Program Files/MySQL/MySQL Server 8.0/bin/mysqldump.exe",
            "C:/Program Files/MySQL/MySQL Server 5.7/bin/mysqldump.exe",
            "C:/Program Files/MySQL/MySQL Server 5.6/bin/mysqldump.exe",
            "C:/Program Files/MySQL/MySQL Server 5.5/bin/mysqldump.exe",
            "C:/Program Files/MySQL/MySQL Server 5.0/bin/mysqldump.exe",
            "mysqldump" // Fallback ke sistem PATH
        };
        for (String path : paths) {
            if (path.equals("mysqldump")) {
                return path;
            }
            java.io.File file = new java.io.File(path);
            if (file.exists()) {
                return path;
            }
        }
        return "mysqldump";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Backup Database");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Proses..........");

        btnOk.setText("Ok");
        btnOk.addActionListener(this::btnOkActionPerformed);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String mysqldumpPath = getMysqldumpPath();
        // Menggunakan array String agar spasi pada nama folder diproses dengan benar oleh OS
        String[] executeCmd = {
            mysqldumpPath,
            "-uroot",
            "penjualan",
            "-r",
            "E:\\Andika Bayu\\KULIAH\\TUGAS KULIAH\\Semester 4\\PEMROGRAMAN BERORIENTASI OBJEK\\Pratikum\\Praktikum 11\\bckpenjual.sql"
        };
        
        try {
            Process runtime = Runtime.getRuntime().exec(executeCmd);
            try {
                int prosescomplete = runtime.waitFor();
                if (prosescomplete == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Backup sukses!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Backup gagal!");
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(frmBackupDatabase.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(frmBackupDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBackupDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmBackupDatabase().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
