/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum11;

/**
 *
 * @author Andika Bayu S
 */
import java.awt.event.MouseEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmKonsumen extends javax.swing.JFrame {
    Connection Con;
    ResultSet RsKons;
    Statement stm;
    Boolean edit = false;
    private Object[][] dataTable = null;
    private final String[] header = {"Kode", "Nama Konsumen", "Alamat", "Kota", "Kode Pos", "Phone", "Email"};
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmKonsumen.class.getName());

    /**
     * Creates new form frmKonsumen
     */
    public frmKonsumen() {
        initComponents();
        open_db();
        baca_data();
        aktif(false);
        setTombol(true);
    }
    
    private void open_db() {
        try {
            // Menggunakan class koneksi eksternal. Silakan sesuaikan nama database Anda (contoh: "db_penjualan")
            // Parameter: host, user, password, nama_db 
            KoneksiMysql kon = new KoneksiMysql("localhost", "root", "", "penjualan");
            Con = kon.getConnection();
        } catch (Exception e) {
            System.out.println("Error Koneksi: " + e);
        }
    }
    
    private void baca_data() {
        try {
            stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            RsKons = stm.executeQuery("SELECT * FROM konsumen");
            ResultSetMetaData meta = RsKons.getMetaData();
            int col = meta.getColumnCount();
            int baris = 0;
            
            while (RsKons.next()) {
                baris = RsKons.getRow();
            }
            
            dataTable = new Object[baris][col]; 
            int x = 0;
            RsKons.beforeFirst();
            while (RsKons.next()) {
                dataTable[x][0] = RsKons.getString("kd_kons"); 
                dataTable[x][1] = RsKons.getString("nm_kons");
                dataTable[x][2] = RsKons.getString("alm_kons"); 
                dataTable[x][3] = RsKons.getString("kota_kons"); 
                dataTable[x][4] = RsKons.getString("kd_pos"); 
                dataTable[x][5] = RsKons.getString("phone"); 
                dataTable[x][6] = RsKons.getString("email"); 
                x++; 
            }
            jTable3.setModel(new DefaultTableModel(dataTable, header)); 
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void setField() {
        int row = jTable3.getSelectedRow(); 
        if (row != -1) { 
            txt_kodekonsumen.setText((String) jTable3.getValueAt(row, 0)); 
            txt_namakomsumen.setText((String) jTable3.getValueAt(row, 1));
            txt_alamat.setText((String) jTable3.getValueAt(row, 2));
            txt_kota.setText((String) jTable3.getValueAt(row, 3));
            txt_kodepos.setText((String) jTable3.getValueAt(row, 4));
            txt_telepon.setText((String) jTable3.getValueAt(row, 5));
            txt_email.setText((String) jTable3.getValueAt(row, 6));
    }
    }

    private void kosong() {
        txt_kodekonsumen.setText(""); 
        txt_namakomsumen.setText(""); 
        txt_alamat.setText(""); 
        txt_kota.setText("");
        txt_kodepos.setText(""); 
        txt_telepon.setText("");
        txt_email.setText("");
    }
    
    private void aktif(boolean x) {
        txt_kodekonsumen.setEditable(x);
        txt_namakomsumen.setEditable(x); 
        txt_alamat.setEditable(x);
        txt_kota.setEditable(x); 
        txt_kodepos.setEditable(x); 
        txt_telepon.setEditable(x);
        txt_email.setEditable(x); 
    }
    
    private void setTombol(boolean t) {
        btn_tambah.setEnabled(t);
        btn_koreksi.setEnabled(t);
        btn_hapus.setEnabled(t); 
        btn_simpan.setEnabled(!t); 
        btn_batal.setEnabled(!t); 
        btn_keluar.setEnabled(t); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lb_kodekonsumen = new javax.swing.JLabel();
        txt_kodekonsumen = new javax.swing.JTextField();
        lb_namakonsumen = new javax.swing.JLabel();
        txt_namakomsumen = new javax.swing.JTextField();
        lb_alamat = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        txt_kota = new javax.swing.JTextField();
        lb_kota = new javax.swing.JLabel();
        lb_kodepos = new javax.swing.JLabel();
        txt_kodepos = new javax.swing.JTextField();
        lb_telepon = new javax.swing.JLabel();
        txt_telepon = new javax.swing.JTextField();
        lb_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btn_tambah = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_koreksi = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Konsumen");

        jLabel1.setText("Data Konsumen");

        lb_kodekonsumen.setText("Kode Konsumen");

        txt_kodekonsumen.addActionListener(this::txt_kodekonsumenActionPerformed);

        lb_namakonsumen.setText("Nama Konsumen");

        lb_alamat.setText("Alamat");

        txt_alamat.addActionListener(this::txt_alamatActionPerformed);

        txt_kota.addActionListener(this::txt_kotaActionPerformed);

        lb_kota.setText("Kota");

        lb_kodepos.setText("KodePos");

        txt_kodepos.addActionListener(this::txt_kodeposActionPerformed);

        lb_telepon.setText("Telepon");

        txt_telepon.addActionListener(this::txt_teleponActionPerformed);

        lb_email.setText("Email");

        txt_email.addActionListener(this::txt_emailActionPerformed);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Konsumen", "Alamat", "Kota", "Kode Pos", "Phone", "Email"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(this::btn_tambahActionPerformed);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(this::btn_simpanActionPerformed);

        btn_koreksi.setText("Koreksi");
        btn_koreksi.addActionListener(this::btn_koreksiActionPerformed);

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(this::btn_hapusActionPerformed);

        btn_batal.setText("Batal");
        btn_batal.addActionListener(this::btn_batalActionPerformed);

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(this::btn_keluarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_namakonsumen)
                            .addComponent(lb_alamat)
                            .addComponent(lb_kodekonsumen))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_kodekonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_namakomsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_telepon)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lb_kodepos)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lb_email)
                                    .addGap(14, 14, 14)))
                            .addComponent(lb_kota))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_kota, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_kodepos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_koreksi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_keluar)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_kodekonsumen)
                    .addComponent(txt_kodekonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_namakonsumen)
                    .addComponent(txt_namakomsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_alamat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_kota)
                    .addComponent(txt_kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kodepos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_kodepos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_telepon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_simpan)
                    .addComponent(btn_koreksi)
                    .addComponent(btn_hapus)
                    .addComponent(btn_batal)
                    .addComponent(btn_keluar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kotaActionPerformed

    private void txt_kodeposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodeposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodeposActionPerformed

    private void txt_teleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_teleponActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_kodekonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kodekonsumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kodekonsumenActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        aktif(true); 
        setTombol(false); 
        kosong(); 
        txt_kodekonsumen.requestFocus();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        aktif(false); 
        setTombol(true); 
        kosong();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_koreksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_koreksiActionPerformed
        // TODO add your handling code here:
        if (txt_kodekonsumen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data pada tabel terlebih dahulu yang ingin dikoreksi!");
            return;
        }
        edit = true; 
        aktif(true); 
        txt_kodekonsumen.setEditable(false); // Primary key dikunci agar tidak bisa diganti saat edit 
        setTombol(false); 
    }//GEN-LAST:event_btn_koreksiActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if (txt_kodekonsumen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data pada tabel yang ingin dihapus!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data konsumen " + txt_kodekonsumen.getText() + "?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String sql = "DELETE FROM konsumen WHERE kd_kons='" + txt_kodekonsumen.getText() + "'"; 
                stm.executeUpdate(sql); 
                baca_data(); // refresh tabel 
                kosong();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if (txt_kodekonsumen.getText().isEmpty() || txt_namakomsumen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode dan Nama Konsumen wajib diisi!");
            return;
        }

        String tKode = txt_kodekonsumen.getText();
        String tNama = txt_namakomsumen.getText();
        String tAlamat = txt_alamat.getText();
        String tKota = txt_kota.getText();
        String tPos = txt_kodepos.getText();
        String tTelp = txt_telepon.getText();
        String tEmail = txt_email.getText();

        try {
            if (edit == true) { // Jika statusnya mengubah data lama 
                String queryUpdate = "UPDATE konsumen SET nm_kons='" + tNama + "', alm_kons='" + tAlamat + 
                                     "', kota_kons='" + tKota + "', kd_pos='" + tPos + "', phone='" + tTelp + 
                                     "', email='" + tEmail + "' WHERE kd_kons='" + tKode + "'";
                stm.executeUpdate(queryUpdate);
                edit = false; // Kembalikan state edit ke false
            } else { // Jika statusnya menambah data baru 
                String queryInsert = "INSERT INTO konsumen VALUES('" + tKode + "', '" + tNama + "', '" + tAlamat + 
                                     "', '" + tKota + "', '" + tPos + "', '" + tTelp + "', '" + tEmail + "')";
                stm.executeUpdate(queryInsert);
            }
            
            baca_data();     // Refresh tampilan JTable
            aktif(false);    // Matikan kolom input kembali 
            setTombol(true); // Nyalakan tombol master kembali 
            kosong();        // Bersihkan data form
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        setField();
    }//GEN-LAST:event_jTable3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmKonsumen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_koreksi;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lb_alamat;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_kodekonsumen;
    private javax.swing.JLabel lb_kodepos;
    private javax.swing.JLabel lb_kota;
    private javax.swing.JLabel lb_namakonsumen;
    private javax.swing.JLabel lb_telepon;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_kodekonsumen;
    private javax.swing.JTextField txt_kodepos;
    private javax.swing.JTextField txt_kota;
    private javax.swing.JTextField txt_namakomsumen;
    private javax.swing.JTextField txt_telepon;
    // End of variables declaration//GEN-END:variables
}