/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum11;

/**
 *
 * @author Andika Bayu S
 */
public class frmMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmMenu.class.getName());

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        menu_datamaster = new javax.swing.JMenu();
        mn_barang = new javax.swing.JMenuItem();
        mn_jual = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mn_keluar = new javax.swing.JMenuItem();
        menu_transaksi = new javax.swing.JMenu();
        mn_trans_jual = new javax.swing.JMenuItem();
        mn_trans_beli = new javax.swing.JMenuItem();
        menu_laporan = new javax.swing.JMenu();
        mn_lappenjualan = new javax.swing.JMenuItem();
        mn_lapkonsumen = new javax.swing.JMenuItem();
        menu_Utility = new javax.swing.JMenu();
        mn_backup = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu_datamaster.setText("Data Master");
        menu_datamaster.addActionListener(this::menu_datamasterActionPerformed);

        mn_barang.setText("Data Barang");
        mn_barang.addActionListener(this::mn_barangActionPerformed);
        menu_datamaster.add(mn_barang);

        mn_jual.setText("Data Konsumen");
        mn_jual.addActionListener(this::mn_jualActionPerformed);
        menu_datamaster.add(mn_jual);
        menu_datamaster.add(jSeparator1);

        mn_keluar.setText("Keluar");
        mn_keluar.addActionListener(this::mn_keluarActionPerformed);
        menu_datamaster.add(mn_keluar);

        jMenuBar2.add(menu_datamaster);

        menu_transaksi.setText("Transaksi");

        mn_trans_jual.setText("Transaksi Penjualan");
        mn_trans_jual.addActionListener(this::mn_trans_jualActionPerformed);
        menu_transaksi.add(mn_trans_jual);

        mn_trans_beli.setText("Transaksi Pembelian");
        mn_trans_beli.addActionListener(this::mn_trans_beliActionPerformed);
        menu_transaksi.add(mn_trans_beli);

        jMenuBar2.add(menu_transaksi);

        menu_laporan.setText("Laporan");

        mn_lappenjualan.setText("Laporan Penjualan");
        mn_lappenjualan.addActionListener(this::mn_lappenjualanActionPerformed);
        menu_laporan.add(mn_lappenjualan);

        mn_lapkonsumen.setText("Laporan Konsumen");
        mn_lapkonsumen.addActionListener(this::mn_lapkonsumenActionPerformed);
        menu_laporan.add(mn_lapkonsumen);

        jMenuBar2.add(menu_laporan);

        menu_Utility.setText("Utility");

        mn_backup.setText("Backup Database");
        mn_backup.addActionListener(this::mn_backupActionPerformed);
        menu_Utility.add(mn_backup);

        jMenuBar2.add(menu_Utility);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_barangActionPerformed
        // TODO add your handling code here:
        new frmBarang().setVisible(true);
    }//GEN-LAST:event_mn_barangActionPerformed

    private void menu_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_transaksiActionPerformed

    private void menu_datamasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_datamasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_datamasterActionPerformed

    private void mn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mn_keluarActionPerformed

    private void mn_jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_jualActionPerformed
        // TODO add your handling code here:
        new frmKonsumen().setVisible(true);
    }//GEN-LAST:event_mn_jualActionPerformed

    private void mn_lappenjualanActionPerformed(java.awt.event.ActionEvent evt) {
        new LapPenjualan().setVisible(true);
    }

    private void mn_lapkonsumenActionPerformed(java.awt.event.ActionEvent evt) {
        new lapKonsumen().setVisible(true);
    }

    private void mn_trans_jualActionPerformed(java.awt.event.ActionEvent evt) {
        new frmTransaksi().setVisible(true);
    }

    private void mn_trans_beliActionPerformed(java.awt.event.ActionEvent evt) {
        new frmPembelian().setVisible(true);
    }

    private void mn_backupActionPerformed(java.awt.event.ActionEvent evt) {
        new frmBackupDatabase().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menu_Utility;
    private javax.swing.JMenuItem mn_backup;
    private javax.swing.JMenu menu_datamaster;
    private javax.swing.JMenu menu_laporan;
    private javax.swing.JMenu menu_transaksi;
    private javax.swing.JMenuItem mn_barang;
    private javax.swing.JMenuItem mn_jual;
    private javax.swing.JMenuItem mn_keluar;
    private javax.swing.JMenuItem mn_lapkonsumen;
    private javax.swing.JMenuItem mn_lappenjualan;
    private javax.swing.JMenuItem mn_trans_beli;
    private javax.swing.JMenuItem mn_trans_jual;
    // End of variables declaration//GEN-END:variables
}
